export const settings = {
    runTests: false,
    threads: 1,
    url: '',
    port: 8123,
    timeout: 6,
    quiet: false,
    initPayload: null,
    wrapperPayload: `{"id":%w:id%,"type":"start","payload":%w:payload%}`,
    disconnectOnTimeout: false,
    responseMatch: null,
    matchResponse: false,
    headerFile: null,
    headers: null,
    wsProto: null,
};