export const settings = {
    runTests: false,
    threads: 3,
    url: '',
    port: 8123,
    timeout: 6,
    initPayload: null,
    wrapperPayload: `{"id":%w:id%,"type":"start","payload":%w:payload%}`,
    disconnectOnTimeout: false,
    ignoreResponse: false,
    responseMatch: null,
    responseIdParam: 'id',
    matchId: true,
    headerFile: null,
    headers: null,
    wsProto: null,
};